# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200']  # Frontend Angular
        allow_headers: ['Content-Type','Accept']  # En-têtes nécessaires
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':  # Appliquer cette configuration pour toutes les routes API
            allow_origin: ['http://localhost:4200']  # Frontend Angular
            allow_headers: ['Content-Type','Accept']  # Autoriser Content-Type
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: true
